server:
  port: 3000

restate:
  sdk:
    http:
      port: 9080
  client:
    base-uri: http://localhost:8080

spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    io.r2dbc.h2: DEBUG